#include "vk_backend.hpp"
#include <cstdlib>
#include <cstdio>
#include <cstring>
#include <vector>

namespace g2p {

void VkBackend::pin_panvk_icd(const std::string& icd_json_path) {
    setenv("VK_DRIVER_FILES", icd_json_path.c_str(), 1);
        setenv("VK_ICD_FILENAMES", icd_json_path.c_str(), 1);
            setenv("VK_LOADER_LAYERS_DISABLE", "~all~", 0);
            }

            static bool device_looks_like_mali(const VkPhysicalDeviceProperties& props) {
                // Cheap heuristic: Mali GPUs report "Mali" in deviceName under panvk.
                    // VK_KHR_driver_properties' driverID would be the precise check, but
                        // early panvk versions may not populate it reliably -- fall back to
                            // substring match, and log the real driver info regardless so it's
                                // visible in output which path was taken.
                                    return std::strstr(props.deviceName, "Mali") != nullptr;
                                    }

                                    DeviceSelectionResult VkBackend::init() {
                                        DeviceSelectionResult result;

                                            VkApplicationInfo app_info{};
                                                app_info.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
                                                    app_info.pApplicationName = "gles2panvk";
                                                        app_info.apiVersion = VK_API_VERSION_1_1;

                                                            VkInstanceCreateInfo instance_info{};
                                                                instance_info.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
                                                                    instance_info.pApplicationInfo = &app_info;
                                                                        // No extensions requested yet -- this milestone doesn't touch a
                                                                            // surface/swapchain. VK_KHR_surface + VK_KHR_android_surface get added
                                                                                // once windowing is wired up.

                                                                                    VkResult res = vkCreateInstance(&instance_info, nullptr, &instance_);
                                                                                        if (res != VK_SUCCESS) {
                                                                                                std::fprintf(stderr, "[gles2panvk] vkCreateInstance failed: %d\n", res);
                                                                                                        return result;
                                                                                                            }

                                                                                                                uint32_t device_count = 0;
                                                                                                                    vkEnumeratePhysicalDevices(instance_, &device_count, nullptr);
                                                                                                                        if (device_count == 0) {
                                                                                                                                std::fprintf(stderr, "[gles2panvk] No Vulkan physical devices found\n");
                                                                                                                                        return result;
                                                                                                                                            }

                                                                                                                                                std::vector<VkPhysicalDevice> devices(device_count);
                                                                                                                                                    vkEnumeratePhysicalDevices(instance_, &device_count, devices.data());

                                                                                                                                                        for (VkPhysicalDevice candidate : devices) {
                                                                                                                                                                VkPhysicalDeviceProperties props{};
                                                                                                                                                                        vkGetPhysicalDeviceProperties(candidate, &props);

                                                                                                                                                                                std::fprintf(stderr, "[gles2panvk] Found device: %s (api %u.%u.%u)\n",
                                                                                                                                                                                                      props.deviceName,
                                                                                                                                                                                                                            VK_API_VERSION_MAJOR(props.apiVersion),
                                                                                                                                                                                                                                                  VK_API_VERSION_MINOR(props.apiVersion),
                                                                                                                                                                                                                                                                        VK_API_VERSION_PATCH(props.apiVersion));

                                                                                                                                                                                                                                                                                if (device_looks_like_mali(props)) {
                                                                                                                                                                                                                                                                                            physical_device_ = candidate;
                                                                                                                                                                                                                                                                                                        result.found_panvk = true;
                                                                                                                                                                                                                                                                                                                    result.device_name = props.deviceName;
                                                                                                                                                                                                                                                                                                                                result.vulkan_api_version = props.apiVersion;
                                                                                                                                                                                                                                                                                                                                            break;
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                            if (physical_device_ == VK_NULL_HANDLE) {
                                                                                                                                                                                                                                                                                                                                                                    std::fprintf(stderr,
                                                                                                                                                                                                                                                                                                                                                                                "[gles2panvk] No Mali/panvk device found among %u device(s) -- "
                                                                                                                                                                                                                                                                                                                                                                                            "falling back to device 0 for now\n", device_count);
                                                                                                                                                                                                                                                                                                                                                                                                    physical_device_ = devices[0];
                                                                                                                                                                                                                                                                                                                                                                                                            VkPhysicalDeviceProperties props{};
                                                                                                                                                                                                                                                                                                                                                                                                                    vkGetPhysicalDeviceProperties(physical_device_, &props);
                                                                                                                                                                                                                                                                                                                                                                                                                            result.device_name = props.deviceName;
                                                                                                                                                                                                                                                                                                                                                                                                                                    result.vulkan_api_version = props.apiVersion;
                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                            // Find a graphics-capable queue family.
                                                                                                                                                                                                                                                                                                                                                                                                                                                uint32_t queue_family_count = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    vkGetPhysicalDeviceQueueFamilyProperties(physical_device_, &queue_family_count, nullptr);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        std::vector<VkQueueFamilyProperties> queue_families(queue_family_count);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            vkGetPhysicalDeviceQueueFamilyProperties(physical_device_, &queue_family_count, queue_families.data());

                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (uint32_t i = 0; i < queue_family_count; ++i) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (queue_families[i].queueFlags & VK_QUEUE_GRAPHICS_BIT) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    graphics_queue_family_ = i;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (graphics_queue_family_ == UINT32_MAX) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        std::fprintf(stderr, "[gles2panvk] No graphics queue family found\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return result;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        float queue_priority = 1.0f;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            VkDeviceQueueCreateInfo queue_info{};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                queue_info.sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    queue_info.queueFamilyIndex = graphics_queue_family_;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        queue_info.queueCount = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            queue_info.pQueuePriorities = &queue_priority;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                VkDeviceCreateInfo device_info{};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    device_info.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        device_info.queueCreateInfoCount = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            device_info.pQueueCreateInfos = &queue_info;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // No device extensions requested yet either -- VK_KHR_swapchain etc.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // get added once required_device_extensions() is actually wired in here.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res = vkCreateDevice(physical_device_, &device_info, nullptr, &device_);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (res != VK_SUCCESS) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    std::fprintf(stderr, "[gles2panvk] vkCreateDevice failed: %d\n", res);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return result;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    vkGetDeviceQueue(device_, graphics_queue_family_, 0, &graphics_queue_);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        std::fprintf(stderr, "[gles2panvk] Device created successfully: %s\n",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          result.device_name.c_str());

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return result;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              void VkBackend::shutdown() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (device_) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          vkDestroyDevice(device_, nullptr);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  device_ = VK_NULL_HANDLE;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (instance_) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  vkDestroyInstance(instance_, nullptr);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          instance_ = VK_NULL_HANDLE;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              static const char* kRequiredExtensions[] = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "VK_KHR_swapchain",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "VK_KHR_maintenance1",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "VK_EXT_extended_dynamic_state",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const char* const* VkBackend::required_device_extensions(uint32_t* count) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              *count = sizeof(kRequiredExtensions) / sizeof(kRequiredExtensions[0]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return kRequiredExtensions;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } // namespace g2p